export type InventoryVehicle = {
  id: string;
  title: string;
  description?: string;
  brand?: string;
  price?: string;
  ratingValue?: string;
  stockLabel?: string;
  compatibleLabel?: string;
  transmission?: string;
  fuelType?: string;
  mileage?: string;
  year?: string;
  location?: string;
  image: string;
};

export const inventoryVehicles: InventoryVehicle[] = [
  {
    id: 'veh-1',
    title: 'Toyota Camry',
    description: 'Clean, well-maintained sedan with a comfortable ride and strong fuel economy.',
    brand: 'Toyota',
    price: '₦21,500,000',
    ratingValue: '4.6',
    stockLabel: 'In stock',
    compatibleLabel: 'Nigerian Used',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    mileage: '62,000 km',
    year: '2021',
    location: 'Abuja',
    image: '/images/vehicles/toyota-camry-white-2021-front.jpg',
  },
  {
    id: 'veh-2',
    title: 'Toyota Camry',
    description: 'Sporty black trim with modern styling and low mileage.',
    brand: 'Toyota',
    price: '₦24,000,000',
    ratingValue: '4.7',
    stockLabel: 'In stock',
    compatibleLabel: 'Foreign Used',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    mileage: '38,000 km',
    year: '2023',
    location: 'Lagos',
    image: '/images/vehicles/toyota-camry-black-2023-front.jpg',
  },
  {
    id: 'veh-3',
    title: 'BMW X5',
    description: 'Premium SUV with commanding presence and a well-appointed interior.',
    brand: 'BMW',
    price: '₦48,500,000',
    ratingValue: '4.8',
    stockLabel: 'In stock',
    compatibleLabel: 'Foreign Used',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    mileage: '45,000 km',
    year: '2021',
    location: 'Abuja',
    image: '/images/vehicles/bmw-x5-2021-white-000.jpg',
  },
  {
    id: 'veh-4',
    title: 'Honda Accord',
    description: 'Reliable midsize sedan known for durability and low maintenance costs.',
    brand: 'Honda',
    price: '₦20,600,000',
    ratingValue: '4.5',
    stockLabel: 'In stock',
    compatibleLabel: 'Nigerian Used',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    mileage: '71,000 km',
    year: '2022',
    location: 'Port Harcourt',
    image: '/images/vehicles/honda-accord-2022-white-001.jpg',
  },
  {
    id: 'veh-5',
    title: 'Hyundai Tucson',
    description: 'Compact SUV offering a great balance of space, comfort, and efficiency.',
    brand: 'Hyundai',
    price: '₦23,200,000',
    ratingValue: '4.4',
    stockLabel: 'Out of stock',
    compatibleLabel: 'Foreign Used',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    mileage: '54,000 km',
    year: '2024',
    location: 'Abuja',
    image: '/images/vehicles/hyundai-tucson-2024-gblack-001.jpg',
  },
  {
    id: 'veh-6',
    title: 'Mercedes-Benz C300',
    description: 'Executive sedan with premium finishing and smooth handling.',
    brand: 'Mercedes-Benz',
    price: '₦42,000,000',
    ratingValue: '4.9',
    stockLabel: 'In stock',
    compatibleLabel: 'Foreign Used',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    mileage: '33,000 km',
    year: '2021',
    location: 'Lagos',
    image: '/images/vehicles/mercedes-benz-c300-2021-black-001.jpg',
  },
  {
    id: 'veh-7',
    title: 'Toyota Corolla',
    description: 'Compact, fuel-efficient, and easy to maintain — a dependable daily driver.',
    brand: 'Toyota',
    price: '₦16,800,000',
    ratingValue: '4.5',
    stockLabel: 'In stock',
    compatibleLabel: 'Nigerian Used',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    mileage: '80,000 km',
    year: '2020',
    location: 'Abuja',
    image: '/images/vehicles/toyota-corolla-blue-2020-front.jpg',
  },
  {
    id: 'veh-8',
    title: 'Toyota Highlander',
    description: 'Spacious three-row SUV ideal for families, with strong towing capability.',
    brand: 'Toyota',
    price: '₦36,900,000',
    ratingValue: '4.7',
    stockLabel: 'In stock',
    compatibleLabel: 'Foreign Used',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    mileage: '29,000 km',
    year: '2021',
    location: 'Lagos',
    image: '/images/vehicles/Toyota Highlander-red-2021-.jpg',
  },
  {
    id: 'veh-9',
    title: 'Ford Ranger',
    description: 'Rugged pickup truck built for work and adventure alike.',
    brand: 'Ford',
    price: '₦29,800,000',
    ratingValue: '4.3',
    stockLabel: 'In stock',
    compatibleLabel: 'Nigerian Used',
    transmission: 'Manual',
    fuelType: 'Diesel',
    mileage: '58,000 km',
    year: '2018',
    location: 'Port Harcourt',
    image: '/images/vehicles/ford-ranger-2018-blue-001.jpg',
  },
  {
    id: 'veh-10',
    title: 'Lexus IS 250',
    description: 'Compact luxury sedan with sharp handling and a refined cabin.',
    brand: 'Lexus',
    price: '₦32,100,000',
    ratingValue: '4.6',
    stockLabel: 'In stock',
    compatibleLabel: 'Foreign Used',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    mileage: '47,000 km',
    year: '2013',
    location: 'Abuja',
    image: '/images/vehicles/Lexus is-250-sliver-2013.jpg',
  },
];
